version: '3.8'

services:
  fastapi_server:
    container_name: fastapi_track
    build: .
    restart: always
    command: "sh -c 'alembic upgrade head && uvicorn fast_app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000'"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file: ".env"
    depends_on:
      - database


  database:
    image: postgres
    restart: always
    container_name: db-track
    env_file: ".env"
    volumes:
      - ./db_docker:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      - POSTGRES_USERNAME=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DATABASE=${DATABASE_NAME}
      - POSTGRES_HOST_AUTH_METHOD= "trust"
      - POSTGRESQL_POSTGRES_PASSWORD= ${DATABASE_PASSWORD}