version: '3.8'

services:
  fastapi_server:
    container_name: fastapi_track
    build: .
    restart: always
    command: "sh -c 'alembic upgrade head && python app/initial_data.py && gunicorn -w 3 -k uvicorn.workers.UvicornWorker app.main:app  --bind 0.0.0.0:8000 --preload --log-level=debug --timeout 120'"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file: ".env"
    depends_on:
      - database


  database:
    image: postgres
    restart: always
    container_name: db-track
    env_file: ".env"
    volumes:
      - truck_pgdata:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      - POSTGRES_USERNAME=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DATABASE=${DATABASE_NAME}
      - POSTGRES_HOST_AUTH_METHOD= "trust"
      - POSTGRESQL_POSTGRES_PASSWORD= ${DATABASE_PASSWORD}

volumes:
  truck_pgdata:
    name: truck_pgdata