"""empty message

Revision ID: 30904967d76b
Revises: 31317d85f693
Create Date: 2023-02-08 13:20:02.894179

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel


# revision identifiers, used by Alembic.
revision = '30904967d76b'
down_revision = '31317d85f693'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ImageMedia_track_id_fkey', 'ImageMedia', type_='foreignkey')
    op.create_foreign_key(None, 'ImageMedia', 'Track', ['track_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ImageMedia', type_='foreignkey')
    op.create_foreign_key('ImageMedia_track_id_fkey', 'ImageMedia', 'Track', ['track_id'], ['id'])
    # ### end Alembic commands ###