"""empty message

Revision ID: 9ba1452dc30f
Revises: f208c8718fb9
Create Date: 2023-02-16 12:03:12.077867

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel


# revision identifiers, used by Alembic.
revision = '9ba1452dc30f'
down_revision = 'f208c8718fb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Blog', sa.Column('link', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('Blog', sa.Column('hashtag', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('Blog', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Blog', 'description')
    op.drop_column('Blog', 'hashtag')
    op.drop_column('Blog', 'link')
    # ### end Alembic commands ###